export default [
  {
    _id: 1,
    name: "Jade",
    category: "Succulents",
    path: "/jade.jpg",
    description: "Test",
  },
  {
    _id: 2,
    name: "Money Plant",
    category: "Tropical and subtropical",
    path: "/money-plant.jpg",
    description: "Test",
  },
  {
    _id: 3,
    name: "Rubber Plant",
    category: "Tropical and subtropical",
    path: "/rubber.jpg",
    description: "Test",
  },
  {
    _id: 4,
    name: "Aloe Vera",
    category: "Succulents",
    path: "/aloe.jpg",
    description: "Test",
  },
  {
    _id: 5,
    name: "Fiddle Leaf Fig",
    category: "Tropical and subtropical",
    path: "/fiddle-leaf-fig.jpg",
    description: "Test",
  },
  {
    _id: 6,
    name: "Pink Syngonium",
    category: "Tropical and subtropical",
    path: "/pink-syngonium.jpg",
    description: "Test",
  },
  {
    _id: 7,
    name: "ZZ Plant",
    category: "Succulents",
    path: "/zz.jpg",
    description: "Test",
  },
  {
    _id: 8,
    name: "Monstera",
    category: "Tropical and subtropical",
    path: "/monstera.jpg",
    description: "Test",
  },
  {
    _id: 9,
    name: "Areca Palm",
    category: "Tropical and subtropical",
    path: "/areca.jpg",
    description: "Test",
  },
  {
    _id: 10,
    name: "Snake Plant",
    category: "Succulents",
    path: "/snake.jpg",
    description: "Test",
  },
  {
    _id: 11,
    name: "Spider Plant",
    category: "Tropical and subtropical",
    path: "/spider.jpg",
    description: "Test",
  },
  {
    _id: 12,
    name: "Peace Lily",
    category: "Tropical and subtropical",
    path: "/peace-lily.jpg",
    description: "Test",
  },
  {
    _id: 13,
    name: "English Ivy",
    category: "Temperates",
    path: "/english-ivy.jpg",
    description: "Test",
  },
  {
    _id: 14,
    name: "Hyacinth",
    category: "Forced bulbs",
    path: "/hyacinth.jpg",
    description: "Test",
  },
];
